package com.cwj.web.pojo;

import java.util.Date;

public class AbAbaoNav {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_abao_nav.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_abao_nav.pid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_abao_nav.name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_abao_nav.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_abao_nav.sort
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_abao_nav.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_abao_nav.update_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_abao_nav.is_del
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_abao_nav.id
     *
     * @return the value of abao_void..ab_abao_nav.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_abao_nav.id
     *
     * @param id the value for abao_void..ab_abao_nav.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_abao_nav.pid
     *
     * @return the value of abao_void..ab_abao_nav.pid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_abao_nav.pid
     *
     * @param pid the value for abao_void..ab_abao_nav.pid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_abao_nav.name
     *
     * @return the value of abao_void..ab_abao_nav.name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_abao_nav.name
     *
     * @param name the value for abao_void..ab_abao_nav.name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_abao_nav.url
     *
     * @return the value of abao_void..ab_abao_nav.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_abao_nav.url
     *
     * @param url the value for abao_void..ab_abao_nav.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_abao_nav.sort
     *
     * @return the value of abao_void..ab_abao_nav.sort
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_abao_nav.sort
     *
     * @param sort the value for abao_void..ab_abao_nav.sort
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_abao_nav.create_time
     *
     * @return the value of abao_void..ab_abao_nav.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_abao_nav.create_time
     *
     * @param createTime the value for abao_void..ab_abao_nav.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_abao_nav.update_time
     *
     * @return the value of abao_void..ab_abao_nav.update_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_abao_nav.update_time
     *
     * @param updateTime the value for abao_void..ab_abao_nav.update_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_abao_nav.is_del
     *
     * @return the value of abao_void..ab_abao_nav.is_del
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_abao_nav.is_del
     *
     * @param isDel the value for abao_void..ab_abao_nav.is_del
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }
}