package com.cwj.web.pojo;

public class AbCircuit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_circuit.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_circuit.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_circuit.id
     *
     * @return the value of abao_void..ab_circuit.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_circuit.id
     *
     * @param id the value for abao_void..ab_circuit.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_circuit.url
     *
     * @return the value of abao_void..ab_circuit.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_circuit.url
     *
     * @param url the value for abao_void..ab_circuit.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }
}