package com.cwj.web.pojo;

public class AbPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_permission.p_id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_permission.p_name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String pName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_permission.p_alias
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String pAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_permission.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_permission.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_permission.created_at
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_permission.updated_at
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_permission.p_id
     *
     * @return the value of abao_void..ab_permission.p_id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_permission.p_id
     *
     * @param pId the value for abao_void..ab_permission.p_id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_permission.p_name
     *
     * @return the value of abao_void..ab_permission.p_name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_permission.p_name
     *
     * @param pName the value for abao_void..ab_permission.p_name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_permission.p_alias
     *
     * @return the value of abao_void..ab_permission.p_alias
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getpAlias() {
        return pAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_permission.p_alias
     *
     * @param pAlias the value for abao_void..ab_permission.p_alias
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setpAlias(String pAlias) {
        this.pAlias = pAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_permission.created
     *
     * @return the value of abao_void..ab_permission.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_permission.created
     *
     * @param created the value for abao_void..ab_permission.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_permission.updated
     *
     * @return the value of abao_void..ab_permission.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_permission.updated
     *
     * @param updated the value for abao_void..ab_permission.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUpdated(Long updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_permission.created_at
     *
     * @return the value of abao_void..ab_permission.created_at
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_permission.created_at
     *
     * @param createdAt the value for abao_void..ab_permission.created_at
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_permission.updated_at
     *
     * @return the value of abao_void..ab_permission.updated_at
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_permission.updated_at
     *
     * @param updatedAt the value for abao_void..ab_permission.updated_at
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUpdatedAt(Long updatedAt) {
        this.updatedAt = updatedAt;
    }
}