package com.cwj.web.pojo;

public class AbRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_role.rid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_role.r_name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String rName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_role.r_alias
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String rAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_role.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_role.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_role.createdAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_role.updatedAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_role.rid
     *
     * @return the value of abao_void..ab_role.rid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_role.rid
     *
     * @param rid the value for abao_void..ab_role.rid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_role.r_name
     *
     * @return the value of abao_void..ab_role.r_name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_role.r_name
     *
     * @param rName the value for abao_void..ab_role.r_name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setrName(String rName) {
        this.rName = rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_role.r_alias
     *
     * @return the value of abao_void..ab_role.r_alias
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getrAlias() {
        return rAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_role.r_alias
     *
     * @param rAlias the value for abao_void..ab_role.r_alias
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setrAlias(String rAlias) {
        this.rAlias = rAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_role.created
     *
     * @return the value of abao_void..ab_role.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_role.created
     *
     * @param created the value for abao_void..ab_role.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_role.updated
     *
     * @return the value of abao_void..ab_role.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_role.updated
     *
     * @param updated the value for abao_void..ab_role.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUpdated(Long updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_role.createdAt
     *
     * @return the value of abao_void..ab_role.createdAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_role.createdAt
     *
     * @param createdat the value for abao_void..ab_role.createdAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreatedat(String createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_role.updatedAt
     *
     * @return the value of abao_void..ab_role.updatedAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_role.updatedAt
     *
     * @param updatedat the value for abao_void..ab_role.updatedAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUpdatedat(String updatedat) {
        this.updatedat = updatedat;
    }
}