package com.cwj.web.pojo;

import java.util.Date;

public class AbSystemlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_systemlog.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_systemlog.time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_systemlog.logdescribe
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String logdescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_systemlog.id
     *
     * @return the value of abao_void..ab_systemlog.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_systemlog.id
     *
     * @param id the value for abao_void..ab_systemlog.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_systemlog.time
     *
     * @return the value of abao_void..ab_systemlog.time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_systemlog.time
     *
     * @param time the value for abao_void..ab_systemlog.time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_systemlog.logdescribe
     *
     * @return the value of abao_void..ab_systemlog.logdescribe
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getLogdescribe() {
        return logdescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_systemlog.logdescribe
     *
     * @param logdescribe the value for abao_void..ab_systemlog.logdescribe
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setLogdescribe(String logdescribe) {
        this.logdescribe = logdescribe;
    }
}