package com.cwj.web.pojo;

public class AbTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_test.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_test.num
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_test.id
     *
     * @return the value of abao_void..ab_test.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_test.id
     *
     * @param id the value for abao_void..ab_test.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_test.num
     *
     * @return the value of abao_void..ab_test.num
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_test.num
     *
     * @param num the value for abao_void..ab_test.num
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setNum(Long num) {
        this.num = num;
    }
}