package com.cwj.web.pojo;

public class AbUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.username
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.email
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.phone
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.password
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.status
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.avatar
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Long updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.createdAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_user.updatedAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private byte[] updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.id
     *
     * @return the value of abao_void..ab_user.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.id
     *
     * @param id the value for abao_void..ab_user.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.username
     *
     * @return the value of abao_void..ab_user.username
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.username
     *
     * @param username the value for abao_void..ab_user.username
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.email
     *
     * @return the value of abao_void..ab_user.email
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.email
     *
     * @param email the value for abao_void..ab_user.email
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.phone
     *
     * @return the value of abao_void..ab_user.phone
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.phone
     *
     * @param phone the value for abao_void..ab_user.phone
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.password
     *
     * @return the value of abao_void..ab_user.password
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.password
     *
     * @param password the value for abao_void..ab_user.password
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.status
     *
     * @return the value of abao_void..ab_user.status
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.status
     *
     * @param status the value for abao_void..ab_user.status
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.avatar
     *
     * @return the value of abao_void..ab_user.avatar
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.avatar
     *
     * @param avatar the value for abao_void..ab_user.avatar
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.created
     *
     * @return the value of abao_void..ab_user.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.created
     *
     * @param created the value for abao_void..ab_user.created
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.updated
     *
     * @return the value of abao_void..ab_user.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Long getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.updated
     *
     * @param updated the value for abao_void..ab_user.updated
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUpdated(Long updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.createdAt
     *
     * @return the value of abao_void..ab_user.createdAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.createdAt
     *
     * @param createdat the value for abao_void..ab_user.createdAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreatedat(String createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_user.updatedAt
     *
     * @return the value of abao_void..ab_user.updatedAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public byte[] getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_user.updatedAt
     *
     * @param updatedat the value for abao_void..ab_user.updatedAt
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUpdatedat(byte[] updatedat) {
        this.updatedat = updatedat;
    }
}