package com.cwj.web.pojo;

import java.util.Date;

public class AbVoidInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.type
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.btype
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String btype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.cover_image
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String coverImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.num
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.grade
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.movieurls
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String movieurls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.director
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String director;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.runing_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String runingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.actor
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String actor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.beon_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Date beonTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.state
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.update_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.is_del
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.sendUrl
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String sendurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info.detil
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String detil;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.id
     *
     * @return the value of abao_void..ab_void_info.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.id
     *
     * @param id the value for abao_void..ab_void_info.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.type
     *
     * @return the value of abao_void..ab_void_info.type
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.type
     *
     * @param type the value for abao_void..ab_void_info.type
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.btype
     *
     * @return the value of abao_void..ab_void_info.btype
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getBtype() {
        return btype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.btype
     *
     * @param btype the value for abao_void..ab_void_info.btype
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setBtype(String btype) {
        this.btype = btype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.name
     *
     * @return the value of abao_void..ab_void_info.name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.name
     *
     * @param name the value for abao_void..ab_void_info.name
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.cover_image
     *
     * @return the value of abao_void..ab_void_info.cover_image
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.cover_image
     *
     * @param coverImage the value for abao_void..ab_void_info.cover_image
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.num
     *
     * @return the value of abao_void..ab_void_info.num
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.num
     *
     * @param num the value for abao_void..ab_void_info.num
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.grade
     *
     * @return the value of abao_void..ab_void_info.grade
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.grade
     *
     * @param grade the value for abao_void..ab_void_info.grade
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.movieurls
     *
     * @return the value of abao_void..ab_void_info.movieurls
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getMovieurls() {
        return movieurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.movieurls
     *
     * @param movieurls the value for abao_void..ab_void_info.movieurls
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setMovieurls(String movieurls) {
        this.movieurls = movieurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.director
     *
     * @return the value of abao_void..ab_void_info.director
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.director
     *
     * @param director the value for abao_void..ab_void_info.director
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.runing_time
     *
     * @return the value of abao_void..ab_void_info.runing_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getRuningTime() {
        return runingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.runing_time
     *
     * @param runingTime the value for abao_void..ab_void_info.runing_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setRuningTime(String runingTime) {
        this.runingTime = runingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.actor
     *
     * @return the value of abao_void..ab_void_info.actor
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.actor
     *
     * @param actor the value for abao_void..ab_void_info.actor
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setActor(String actor) {
        this.actor = actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.beon_time
     *
     * @return the value of abao_void..ab_void_info.beon_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Date getBeonTime() {
        return beonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.beon_time
     *
     * @param beonTime the value for abao_void..ab_void_info.beon_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setBeonTime(Date beonTime) {
        this.beonTime = beonTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.state
     *
     * @return the value of abao_void..ab_void_info.state
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.state
     *
     * @param state the value for abao_void..ab_void_info.state
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.create_time
     *
     * @return the value of abao_void..ab_void_info.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.create_time
     *
     * @param createTime the value for abao_void..ab_void_info.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.update_time
     *
     * @return the value of abao_void..ab_void_info.update_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.update_time
     *
     * @param updateTime the value for abao_void..ab_void_info.update_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.is_del
     *
     * @return the value of abao_void..ab_void_info.is_del
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.is_del
     *
     * @param isDel the value for abao_void..ab_void_info.is_del
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.sendUrl
     *
     * @return the value of abao_void..ab_void_info.sendUrl
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getSendurl() {
        return sendurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.sendUrl
     *
     * @param sendurl the value for abao_void..ab_void_info.sendUrl
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setSendurl(String sendurl) {
        this.sendurl = sendurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info.detil
     *
     * @return the value of abao_void..ab_void_info.detil
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getDetil() {
        return detil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info.detil
     *
     * @param detil the value for abao_void..ab_void_info.detil
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setDetil(String detil) {
        this.detil = detil;
    }
}