package com.cwj.web.pojo;

import java.util.Date;

public class AbVoidInfoSon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info_son.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info_son.vid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Integer vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info_son.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info_son.sort
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column abao_void..ab_void_info_son.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info_son.id
     *
     * @return the value of abao_void..ab_void_info_son.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info_son.id
     *
     * @param id the value for abao_void..ab_void_info_son.id
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info_son.vid
     *
     * @return the value of abao_void..ab_void_info_son.vid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info_son.vid
     *
     * @param vid the value for abao_void..ab_void_info_son.vid
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info_son.url
     *
     * @return the value of abao_void..ab_void_info_son.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info_son.url
     *
     * @param url the value for abao_void..ab_void_info_son.url
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info_son.sort
     *
     * @return the value of abao_void..ab_void_info_son.sort
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info_son.sort
     *
     * @param sort the value for abao_void..ab_void_info_son.sort
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setSort(String sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column abao_void..ab_void_info_son.create_time
     *
     * @return the value of abao_void..ab_void_info_son.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column abao_void..ab_void_info_son.create_time
     *
     * @param createTime the value for abao_void..ab_void_info_son.create_time
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}