package com.cwj.web.mapper;

import com.cwj.web.pojo.AbAbaoNav;
import java.util.List;

public interface AbAbaoNavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_abao_nav
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_abao_nav
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbAbaoNav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_abao_nav
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbAbaoNav selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_abao_nav
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbAbaoNav> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_abao_nav
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbAbaoNav record);
}