package com.cwj.web.mapper;

import com.cwj.web.pojo.AbCircuit;
import java.util.List;

public interface AbCircuitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_circuit
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_circuit
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbCircuit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_circuit
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbCircuit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_circuit
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbCircuit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_circuit
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbCircuit record);
}