package com.cwj.web.mapper;

import com.cwj.web.pojo.AbRole;
import java.util.List;

public interface AbRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_role
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_role
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_role
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbRole selectByPrimaryKey(Integer rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_role
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_role
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbRole record);
}