package com.cwj.web.mapper;

import com.cwj.web.pojo.AbSeckillGoods;
import java.util.List;

public interface AbSeckillGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_goods
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_goods
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbSeckillGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_goods
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbSeckillGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_goods
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbSeckillGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_goods
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbSeckillGoods record);
}