package com.cwj.web.mapper;

import com.cwj.web.pojo.AbSeckillOrder;
import java.util.List;

public interface AbSeckillOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_order
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_order
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbSeckillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_order
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbSeckillOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_order
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbSeckillOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_seckill_order
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbSeckillOrder record);
}