package com.cwj.web.mapper;

import com.cwj.web.pojo.AbSystemlog;
import java.util.List;

public interface AbSystemlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_systemlog
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_systemlog
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbSystemlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_systemlog
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbSystemlog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_systemlog
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbSystemlog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_systemlog
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbSystemlog record);
}