package com.cwj.web.mapper;

import com.cwj.web.pojo.AbTest;
import java.util.List;

public interface AbTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_test
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_test
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_test
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_test
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbTest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_test
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbTest record);
}