package com.cwj.web.mapper;

import com.cwj.web.pojo.AbUser;
import java.util.List;

public interface AbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_user
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_user
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_user
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_user
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbUser> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_user
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbUser record);
}