package com.cwj.web.mapper;

import com.cwj.web.pojo.AbVoidInfoSon;
import java.util.List;

public interface AbVoidInfoSonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info_son
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info_son
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbVoidInfoSon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info_son
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbVoidInfoSon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info_son
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbVoidInfoSon> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info_son
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbVoidInfoSon record);
}