package com.cwj.web.mapper;

import com.cwj.web.pojo.AbVoidInfo;
import java.util.List;

public interface AbVoidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int insert(AbVoidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    AbVoidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    List<AbVoidInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table abao_void..ab_void_info
     *
     * @mbggenerated Fri Jul 03 16:42:05 CST 2020
     */
    int updateByPrimaryKey(AbVoidInfo record);
}